language: ruby
rvm:
  - "1.9.3"
#  - "2.1.0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/site.example.yml config/site.yml
  - bundle exec rake db:migrate RAILS_ENV=test
script: xvfb-run bundle exec rspec spec/features/request_process_spec.rb
